[
  {
    benchAddress: "Brewer Street",
    benchName: "Dreamcatcher Bench",
    capacity: 1,
    endTime: [Object],
    startTime: [Object],
    user_1: "sedohaHzw7MqMeu7qn0lDNJCsb23",
    user_2: null,
  },
  {
    benchAddress: "Brewer Street",
    benchName: "Dreamcatcher Bench",
    capacity: 2,
    endTime: [Object],
    startTime: [Object],
    user_1: null,
    user_2: null,
  },
  {
    benchAddress: "Brewer Street",
    benchName: "Dreamcatcher Bench",
    capacity: 2,
    endTime: [Object],
    startTime: [Object],
    user_1: null,
    user_2: null,
  },
  {
    benchAddress: "Brewer Street",
    benchName: "Dreamcatcher Bench",
    capacity: 2,
    endTime: [Object],
    startTime: [Object],
    user_1: null,
    user_2: null,
  },
  {
    benchAddress: "Brewer Street",
    benchName: "Dreamcatcher Bench",
    capacity: 2,
    endTime: [Object],
    startTime: [Object],
    user_1: null,
    user_2: null,
  },
  {
    benchAddress: "Brewer Street",
    benchName: "Dreamcatcher Bench",
    capacity: 2,
    endTime: [Object],
    startTime: [Object],
    user_1: null,
    user_2: null,
  },
  {
    benchAddress: "Brewer Street",
    benchName: "Dreamcatcher Bench",
    capacity: 2,
    endTime: [Object],
    startTime: [Object],
    user_1: null,
    user_2: null,
  },
  {
    benchAddress: "Brewer Street",
    benchName: "Dreamcatcher Bench",
    capacity: 2,
    endTime: [Object],
    startTime: [Object],
    user_1: null,
    user_2: null,
  },
];
